// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class EmpleosdisponiblesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pBQA22BuscartrabajosCamposvacios() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    js.executeScript("window.scrollTo(0,1123)");
    js.executeScript("window.scrollTo(0,2040)");
    {
      WebElement element = driver.findElement(By.cssSelector("input:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
  @Test
  public void pBQA23Buscartrabajos1parametro() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    js.executeScript("window.scrollTo(0,2346)");
    driver.findElement(By.id("search_location")).click();
    driver.findElement(By.id("search_location")).sendKeys("Bogota");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
  }
  @Test
  public void pBQA24Buscartrabajos2parametros() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    js.executeScript("window.scrollTo(0,993)");
    js.executeScript("window.scrollTo(0,1632)");
    driver.findElement(By.id("search_location")).click();
    driver.findElement(By.id("search_location")).sendKeys("Bogota");
    driver.findElement(By.id("search_keywords")).click();
    driver.findElement(By.id("search_keywords")).sendKeys("Tester");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
  }
  @Test
  public void pBQA25Visualizacindelaoferta() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    js.executeScript("window.scrollTo(0,2646)");
    js.executeScript("window.scrollTo(0,2550)");
    driver.findElement(By.cssSelector(".post-7457 h3")).click();
    {
      WebElement element = driver.findElement(By.linkText("Medellín"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
