// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class GeneralidadesdelacalidaddelsoftwareTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pBQA4EnlaceModelodecalidaddesoftware() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    js.executeScript("window.scrollTo(0,494)");
    js.executeScript("window.scrollTo(0,2856)");
    driver.findElement(By.linkText("Modelo de calidad de software")).click();
  }
  @Test
  public void pBQA5EnlaceDiferenciaentrecalidaddesoftwareypruebas() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    driver.findElement(By.linkText("Diferencia entre calidad de software y pruebas")).click();
  }
  @Test
  public void pBQA7EnlaceElsoftwareenlaeconomaactual() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    {
      WebElement element = driver.findElement(By.cssSelector(".mob-standard-logo"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,1179)");
    driver.findElement(By.linkText("El software en la economía actual")).click();
  }
  @Test
  public void pBQA9EnlaceLoserroresdelsoftware() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    driver.findElement(By.linkText("Los errores del software")).click();
  }
  @Test
  public void pBQA8EnlaceCalidaddesoftware() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    js.executeScript("window.scrollTo(0,798)");
    js.executeScript("window.scrollTo(0,2856)");
    driver.findElement(By.linkText("Calidad de software")).click();
  }
}
