// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class SobrelaGerenciadeProyectosTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pBQA20EnlaceFundamentosdelagerenciadeproyectosendesarrollodesoftware() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    js.executeScript("window.scrollTo(0,1291)");
    js.executeScript("window.scrollTo(0,3829)");
    driver.findElement(By.linkText("Fundamentos de la gerencia de proyectos en desarrollo de software")).click();
  }
  @Test
  public void pBQA21EnlaceCulessonlasactividadesdelaGestindeProyectos() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    js.executeScript("window.scrollTo(0,3412)");
    driver.findElement(By.linkText("¿Cuáles son las actividades de la Gestión de Proyectos?")).click();
    {
      WebElement element = driver.findElement(By.linkText("¿Cuáles son las actividades de la Gestión de Proyectos?"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("¿Cuáles son las actividades de la Gestión de Proyectos?"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
