// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class SobrelaIngenieradeSoftwareTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pBQA10EnlaceFundamentosingenieradesoftware() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    js.executeScript("window.scrollTo(0,3162)");
    driver.findElement(By.linkText("Fundamentos ingeniería de software")).click();
  }
  @Test
  public void pBQA11EnlaceManualprcticodeSQL() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    js.executeScript("window.scrollTo(0,1968)");
    js.executeScript("window.scrollTo(0,3754)");
    driver.findElement(By.linkText("Manual práctico de SQL")).click();
  }
  @Test
  public void pBQA12EnlaceQuesprogramacinporNcapas() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    driver.findElement(By.linkText("¿Qué es programación por Ncapas?")).click();
  }
  @Test
  public void pBQA13EnlaceAlgoritmosdesoftware() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    js.executeScript("window.scrollTo(0,723)");
    driver.findElement(By.linkText("Algoritmos de software")).click();
  }
  @Test
  public void pBQA14EnlacePrincipiosdeprogramacin() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    driver.findElement(By.linkText("Principios de programación")).click();
  }
  @Test
  public void pBQA15EnlaceMarcosdetrabajodesoftwaregilestradicionales() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    js.executeScript("window.scrollTo(0,2621)");
    js.executeScript("window.scrollTo(0,3162)");
    driver.findElement(By.linkText("Marcos de trabajo de software: ágiles/tradicionales")).click();
  }
}
