// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class SobrelaspruebasdesoftwareenelcontextodeldesarrollodesoftwareTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pBQA16EnlaceMarcosdetrabajodeprueba() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    js.executeScript("window.scrollTo(0,3390)");
    driver.findElement(By.linkText("Marcos de trabajo de pruebas")).click();
  }
  @Test
  public void pBQA17EnlaceQusonlosriesgosdelproyectoydeproducto() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    js.executeScript("window.scrollTo(0,312)");
    driver.findElement(By.linkText("¿Qué son los riesgos del proyecto y de producto?")).click();
  }
  @Test
  public void pBQA18EnlaceTcnicasdecajanegra() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    js.executeScript("window.scrollTo(0,105)");
    js.executeScript("window.scrollTo(0,1911)");
    driver.findElement(By.linkText("Técnicas de caja negra")).click();
  }
  @Test
  public void pBQA19EnlaceFoundationLevelTcnicas() {
    driver.get("https://www.choucairtesting.com/empleos-2/");
    driver.manage().window().setSize(new Dimension(771, 693));
    js.executeScript("window.scrollTo(0,986)");
    js.executeScript("window.scrollTo(0,2448)");
    driver.findElement(By.linkText("Foundation Level – Técnicas")).click();
  }
}
